### ISSUE TITLE
Dont Open

### ISSUE THREAD

**Issue by kaiaky** [Triky313/AlbionOnline-StatisticsAnalysis#226]
**Describe the bug**
i have problem after update. I click on .exe and do nothing. Dont launch the program and dont make any error message

The program was working properly until the recent update. I clicked to update and it no longer works. The program does not open and no error message appears

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 21H2

**Comment by Triky313** [comment]
Please download the newest version of the tool and retry to start

**Comment by kaiaky** [comment]
I do this, but dont open…

Question: when i download the newest version, i need delete another? Or i
can only extract and substitute?

Em qua., 1 de fev. de 2023 às 15:17, Aaron Schultz ***@***.***>
escreveu:

**Comment by pavlli** [comment]
I have same problem. When I download latest version from web, tool is starting without problems. But then it offers update, and after update it doesn't start again
I have Windows 11 Pro 21H2

**Comment by Triky313** [comment]
Can you upload the error log file here, it's in the tools folder in the logs directory

**Comment by pavlli** [comment]
> Can you upload the error log file here, it's in the tools folder in the logs directory

Sorry I deleted previous error one, when I copy version from web again. And now, when I click update on version 5.14.2 it doesn't offer update to 5.15.8

**Comment by Triky313** [comment]
What can also be that the Windows version causes a problem. I think the latest version is Windows 11 22H2, can you install it?

I tested it with Windows 11 Pro 22H2 and it all worked.

**Comment by kaiaky** [comment]
> Can you upload the error log file here, it's in the tools folder in the logs directory

the last two errors i have:

ERROR 2023-01-28 13:26:18 - [20] message:Device_OnPacketArrival 
 method:Device_OnPacketArrival 
 stacktrace:SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch > SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch > SharpPcap.LibPcap.PcapDevice.PacketHandler > SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent > StatisticsAnalysisTool.Network.NetworkManager.Device_OnPacketArrival 
 line: 103 
System.ArgumentOutOfRangeException: Value must be non-negative and less than or equal to Int32.MaxValue. (Parameter 'count')
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at PhotonPackageParser.PhotonParser.HandleCommand(Byte[] source, Int32& offset)
   at PhotonPackageParser.PhotonParser.ReceivePacket(Byte[] payload)
   at StatisticsAnalysisTool.Network.NetworkManager.Device_OnPacketArrival(Object sender, PacketCapture e) in C:\Users\schul\Documents\GitHub\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\Network\NetworkManager.cs:line 123
ERROR 2023-01-29 12:33:31 - [20] message:Device_OnPacketArrival 
 method:Device_OnPacketArrival 
 stacktrace:SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch > SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch > SharpPcap.LibPcap.PcapDevice.PacketHandler > SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent > StatisticsAnalysisTool.Network.NetworkManager.Device_OnPacketArrival 
 line: 103 
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Protocol16.Protocol16Stream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at PhotonPackageParser.PhotonParser.HandleSendReliable(Byte[] source, Int32& offset, Int32& commandLength)
   at PhotonPackageParser.PhotonParser.HandleCommand(Byte[] source, Int32& offset)
   at PhotonPackageParser.PhotonParser.ReceivePacket(Byte[] payload)
   at StatisticsAnalysisTool.Network.NetworkManager.Device_OnPacketArrival(Object sender, PacketCapture e) in C:\Users\schul\Documents\GitHub\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\Network\NetworkManager.cs:line 123

**Comment by Triky313** [comment]
What version do you have?

**Comment by kaiaky** [comment]
my windows is updated... Latest version T_T

Em sáb., 4 de fev. de 2023 às 10:36, Aaron Schultz ***@***.***>
escreveu:

**Comment by Triky313** [comment]
Sorry i mean the tool version.
