### ISSUE TITLE
The tracker stops due to an OverflowException - the tracker should restart automatically

### ISSUE THREAD

**Issue by Triky313** [Triky313/AlbionOnline-StatisticsAnalysis#37]
ERROR 2021-04-15 20:58:46 - [35] message:PacketHandler 
 method:PacketHandler 
 stacktrace:SharpPcap.LibPcap.Windows.pcap_dispatch > SharpPcap.LibPcap.PcapDevice.PacketHandler > SharpPcap.Npcap.NpcapDevice.SendPacketArrivalEvent > SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent > StatisticsAnalysisTool.Network.NetworkManager.PacketHandler 
 line: 134 
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Protocol16.Protocol16Stream..ctor(Int32 size)
   at PhotonPackageParser.PhotonParser.HandleSendReliable(Byte[] source, Int32& offset, Int32& commandLength)
   at PhotonPackageParser.PhotonParser.HandleCommand(Byte[] source, Int32& offset)
   at PhotonPackageParser.PhotonParser.ReceivePacket(Byte[] payload)
   at Albion.Network.AlbionParser.Albion.Network.IPhotonReceiver.ReceivePacket(Byte[] payload)
   at StatisticsAnalysisTool.Network.NetworkManager.PacketHandler(Object sender, CaptureEventArgs e) in C:\Users\schul\Documents\GitHub\AlbionOnline-StatisticsAnalysis\StatisticsAnalysisTool\StatisticsAnalysisTool\Network\NetworkManager.cs:line 129

**Comment by Triky313** [comment]
After carefully checking, I came to the decision not to implement an automatic switch-on of the tracker after a exception.
It is more difficult to turn the tracker on automatically than it does manually.
