### ISSUE TITLE
Program crashes randomly

### ISSUE THREAD

**Issue by SilvioMX** [Triky313/AlbionOnline-StatisticsAnalysis#452]
the program crashes randomly, similar to the crash report of two weeks ago i saw in the solved issues

 - OS: Windows 10
 - Tool Version  v7.0.2.19511

I start it as admin

**Comment by Triky313** [comment]
Can you send me the error log from the logs folder please?

**Comment by SilvioMX** [comment]
2023-10-19 01:46:03.015 +02:00 [INF] Tool started with v7.0.2.19511
2023-10-19 01:46:08.575 +02:00 [INF] NetworkManager - Added Socket |: AddressFamily: InterNetwork, LocalEndPoint: 10.5.0.2:0, Connected: False, Available: 0, Blocking: True, IsBound: True, ReceiveBufferSize: 65536, SendBufferSize: 65536, Ttl: 128
2023-10-19 01:46:08.577 +02:00 [INF] NetworkManager - Added Socket |: AddressFamily: InterNetwork, LocalEndPoint: 192.168.1.219:0, Connected: False, Available: 0, Blocking: True, IsBound: True, ReceiveBufferSize: 65536, SendBufferSize: 65536, Ttl: 128
2023-10-19 01:51:14.303 +02:00 [FTL] StatisticsAnalysisTool.App
System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at StatisticsAnalysisTool.Network.NetworkManager.OnReceive(IAsyncResult ar) in D:\a\AlbionOnline-StatisticsAnalysis\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\Network\NetworkManager.cs:line 243
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
