### ISSUE TITLE
I can't open this, and I keep reporting an error, which is an error log

### ISSUE THREAD

**Issue by kaiyuan0690** [Triky313/AlbionOnline-StatisticsAnalysis#538]
2024-10-26 22:52:06.070 +08:00 [INF] Tool started with v7.7.4.27068
2024-10-26 22:52:07.181 +08:00 [INF] OS Version: Microsoft Windows 10.0.19045 - X64 | Processor: AMD Ryzen 5 5500GT with Radeon Graphics         | Video: AMD Radeon(TM) Graphics | Is Admin: False | Is Debug: False | Active Networks: WLAN, Loopback Pseudo-Interface 1
2024-10-26 22:52:09.370 +08:00 [FTL] StatisticsAnalysisTool.App
System.Net.Http.HttpRequestException: 在其上下文中，该请求的地址无效。 (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (10049): 在其上下文中，该请求的地址无效。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at StatisticsAnalysisTool.Common.HttpClientUtils.IsUrlAccessible(String url) in D:\a\AlbionOnline-StatisticsAnalysis\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\Common\HttpClientUtils.cs:line 70
   at StatisticsAnalysisTool.Common.AutoUpdateController.AutoUpdateAsync(Boolean reportErrors) in D:\a\AlbionOnline-StatisticsAnalysis\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\Common\AutoUpdateController.cs:line 28
   at StatisticsAnalysisTool.App.OnStartup(StartupEventArgs e) in D:\a\AlbionOnline-StatisticsAnalysis\AlbionOnline-StatisticsAnalysis\src\StatisticsAnalysisTool\App.xaml.cs:line 42
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at StatisticsAnalysisTool.App.Main()

**Comment by Triky313** [comment]
It seems that the page raw.githubusercontent.com is blocked in your network.
The tool cannot download required files and therefore there are problems.
